const PREFIX = 'MythicResizableGrid';
export const classes = {
    root: `${PREFIX}-root`,
    grid: `${PREFIX}-grid`,
    headerCellRow: `${PREFIX}-headerCellRow`,
    headerCell: `${PREFIX}-headerCell`,
    headerCellNoSort: `${PREFIX}-headerCellNoSort`,
    headerContent: `${PREFIX}-headerContent`,
    headerLabel: `${PREFIX}-headerLabel`,
    headerActions: `${PREFIX}-headerActions`,
    headerIndicator: `${PREFIX}-headerIndicator`,
    headerFilterIcon: `${PREFIX}-headerFilterIcon`,
    headerSortIcon: `${PREFIX}-headerSortIcon`,
    headerResizeHandle: `${PREFIX}-headerResizeHandle`,
    headerResizeHandleActive: `${PREFIX}-headerResizeHandleActive`,
    resizeGuide: `${PREFIX}-resizeGuide`,
    hoveredRow: `${PREFIX}-hoveredRow`,
    contextRow: `${PREFIX}-contextRow`,
    rowFirstCell: `${PREFIX}-rowFirstCell`,
    rowLastCell: `${PREFIX}-rowLastCell`,
    rowInteractive: `${PREFIX}-rowInteractive`,
    cell: `${PREFIX}-cell`,
    cellInner: `${PREFIX}-cellInner`,
}
