const PREFIX = 'MythicResizableGrid';
export const classes = {
    root: `${PREFIX}-root flex-fill h-full min-h-0 min-w-0 overflow-hidden relative rounded w-full`,
    grid: `${PREFIX}-grid`,
    headerCellRow: `${PREFIX}-headerCellRow flex flex-row`,
    headerCell: `${PREFIX}-headerCell cursor-pointer items-center flex justify-between min-w-0 overflow-hidden relative`,
    headerCellNoSort: `${PREFIX}-headerCellNoSort`,
    headerContent: `${PREFIX}-headerContent items-center flex gap-3 justify-between min-w-0 w-full`,
    headerLabel: `${PREFIX}-headerLabel min-w-0 truncate`,
    headerActions: `${PREFIX}-headerActions items-center inline-flex flex-none gap-2 min-w-0`,
    headerIndicator: `${PREFIX}-headerIndicator items-center inline-flex flex-none justify-center rounded`,
    headerFilterIcon: `${PREFIX}-headerFilterIcon cursor-pointer`,
    headerSortIcon: `${PREFIX}-headerSortIcon`,
    headerResizeHandle: `${PREFIX}-headerResizeHandle`,
    headerResizeHandleActive: `${PREFIX}-headerResizeHandleActive`,
    resizeGuide: `${PREFIX}-resizeGuide`,
    hoveredRow: `${PREFIX}-hoveredRow`,
    contextRow: `${PREFIX}-contextRow`,
    rowFirstCell: `${PREFIX}-rowFirstCell`,
    rowLastCell: `${PREFIX}-rowLastCell`,
    rowInteractive: `${PREFIX}-rowInteractive`,
    cell: `${PREFIX}-cell items-center flex min-w-0 relative truncate`,
    cellInner: `${PREFIX}-cellInner items-center flex min-w-0 truncate w-full whitespace-nowrap`,
}
