From itsafeaturemythic/mythic_react:0.0.4

COPY mythic/ /mythic/

#From node:15.11.0-alpine3.10

#WORKDIR /mythic
#COPY ["mythic/package.json", "/mythic/package.json"]
#RUN npm install --legacy-peer-deps
#CMD ["npm", "start"]
