From itsafeaturemythic/mythic_postgres:0.0.1
COPY ["pg_hba.conf", "/var/lib/postgresql/pg_hba.conf"]
COPY ["configuration.sql", "/docker-entrypoint-initdb.d/configuration.sql"]
COPY ["configuration.sh", "/docker-entrypoint-initdb.d/configuration.sh"]