package webcontroller

import (
	"fmt"
	"net/http"
	"time"

	"github.com/its-a-feature/Mythic/authentication/mythicjwt"
	"github.com/its-a-feature/Mythic/rabbitmq"

	"github.com/gin-gonic/gin"
	"github.com/its-a-feature/Mythic/authentication"
	"github.com/its-a-feature/Mythic/database"
	databaseStructs "github.com/its-a-feature/Mythic/database/structs"
	"github.com/lib/pq"
)

type GenerateAPITokenInput struct {
	Input GenerateAPIToken `json:"input" binding:"required"`
}

type GenerateAPIToken struct {
	OperatorID int      `json:"operator_id"`
	Name       string   `json:"name"`
	Scopes     []string `json:"scopes"`
}

type GenerateAPITokenResponse struct {
	Status       string    `json:"status"`
	TokenType    string    `json:"token_type"`
	TokenValue   string    `json:"token_value"`
	Error        string    `json:"error"`
	ID           int       `json:"id"`
	OperatorID   int       `json:"operator_id"`
	Name         string    `json:"name"`
	CreatedBy    int       `json:"created_by"`
	Scopes       []string  `json:"scopes"`
	CreationTime time.Time `json:"creation_time"`
}

func GenerateAPITokenWebhook(c *gin.Context) {
	// get variables from the POST request
	var input GenerateAPITokenInput
	err := c.ShouldBindJSON(&input)
	if err != nil {
		c.JSON(http.StatusBadRequest, GenerateAPITokenResponse{
			Status: "error",
			Error:  err.Error(),
		})
		return
	}
	// get the associated database information
	// an api token is just the same as a JWT
	userID, err := GetUserIDFromGin(c)
	if err != nil {
		c.JSON(http.StatusOK, GenerateAPITokenResponse{
			Status: "error",
			Error:  err.Error(),
		})
		return
	}
	defaultName := "autogenerated"
	createdBy := userID
	if input.Input.OperatorID > 0 && input.Input.OperatorID != userID {
		targetOperator := databaseStructs.Operator{ID: input.Input.OperatorID}
		err = database.DB.Get(&targetOperator, "select * from operator where id = $1", targetOperator.ID)
		if err != nil {
			c.JSON(http.StatusOK, GenerateAPITokenResponse{
				Status: "error",
				Error:  err.Error(),
			})
			return
		}
		issuingUser := databaseStructs.Operator{ID: userID}
		err = database.DB.Get(&issuingUser, "select * from operator where id = $1", issuingUser.ID)
		if err != nil {
			c.JSON(http.StatusOK, GenerateAPITokenResponse{
				Status: "error",
				Error:  err.Error(),
			})
			return
		}
		if targetOperator.AccountType != databaseStructs.AccountTypeBot {
			c.JSON(http.StatusOK, GenerateAPITokenResponse{
				Status: "error",
				Error:  "account type is not bot",
			})
			return
		}
		issuingUserOperatorOperation := databaseStructs.Operatoroperation{}
		err = database.DB.Get(&issuingUserOperatorOperation, `SELECT
		id, view_mode
		FROM operatoroperation 
		WHERE operatoroperation.operator_id=$1 and operatoroperation.operation_id=$2`,
			issuingUser.ID, targetOperator.CurrentOperationID.Int64)
		if err != nil {
			c.JSON(http.StatusOK, UpdateCurrentOperationResponse{
				Status: "error",
				Error:  "Cannot generate an apitoken for a bot that's a member of an operation you don't belong to",
			})
			return
		}
		if issuingUserOperatorOperation.ViewMode == database.OPERATOR_OPERATION_VIEW_MODE_SPECTATOR {
			c.JSON(http.StatusOK, GenerateAPITokenResponse{
				Status: "error",
				Error:  "cannot generate an apitoken for a bot as a spectator",
			})
			return
		}
		userID = targetOperator.ID
		defaultName = fmt.Sprintf("generated by %s", issuingUser.Username)
	}
	if input.Input.Name != "" {
		defaultName = input.Input.Name
	}
	claims, err := authentication.GetClaims(c)
	if err != nil {
		c.JSON(http.StatusForbidden, gin.H{"error": "Authentication Failed"})
		return
	}
	authType := mythicjwt.AUTH_METHOD_API
	if claims.EventStepInstanceID > 0 {
		authType = mythicjwt.AUTH_METHOD_EVENT
	}
	normalizedScopes, err := mythicjwt.NormalizeAPITokenScopes(input.Input.Scopes)
	if err != nil {
		c.JSON(http.StatusOK, GenerateAPITokenResponse{
			Status: "error",
			Error:  err.Error(),
		})
		return
	}
	if err = mythicjwt.CanGrantAPITokenScopes(claims.Scopes, normalizedScopes); err != nil {
		c.JSON(http.StatusOK, GenerateAPITokenResponse{
			Status: "error",
			Error:  err.Error(),
		})
		return
	}
	// save off the access_token as an API token and then return it
	apiToken := databaseStructs.Apitokens{
		TokenValue: "",
		OperatorID: userID,
		TokenType:  authType,
		Active:     true,
		Name:       defaultName,
		Scopes:     pq.StringArray(normalizedScopes),
		CreatedBy:  createdBy,
	}
	if authType == mythicjwt.AUTH_METHOD_EVENT {
		apiToken.EventStepInstanceID.Valid = true
		apiToken.EventStepInstanceID.Int64 = int64(claims.EventStepInstanceID)
	}
	statement, err := database.DB.PrepareNamed(`INSERT INTO apitokens
		(token_value, operator_id, token_type, active, "name", scopes, created_by, eventstepinstance_id)
		VALUES
		(:token_value, :operator_id, :token_type, :active, :name, :scopes, :created_by, :eventstepinstance_id)
		RETURNING id`)
	if err != nil {
		c.JSON(http.StatusOK, GenerateAPITokenResponse{
			Status: "error",
			Error:  err.Error(),
		})
		return
	}
	err = statement.Get(&apiToken.ID, apiToken)
	if err != nil {
		c.JSON(http.StatusOK, GenerateAPITokenResponse{
			Status: "error",
			Error:  err.Error(),
		})
		return
	}
	accessToken, storedAPITokenValue, err := mythicjwt.GenerateOpaqueAPIToken()
	if err != nil {
		c.JSON(http.StatusOK, GenerateAPITokenResponse{
			Status: "error",
			Error:  err.Error(),
		})
		return
	}
	apiToken.TokenValue = storedAPITokenValue
	_, err = database.DB.Exec(`UPDATE apitokens SET token_value=$1 WHERE id=$2`, apiToken.TokenValue, apiToken.ID)
	if err != nil {
		c.JSON(http.StatusOK, GenerateAPITokenResponse{
			Status: "error",
			Error:  err.Error(),
		})
		return
	}
	c.JSON(http.StatusOK, GenerateAPITokenResponse{
		Status:       "success",
		TokenValue:   accessToken,
		OperatorID:   userID,
		ID:           apiToken.ID,
		Name:         apiToken.Name,
		CreatedBy:    apiToken.CreatedBy,
		TokenType:    apiToken.TokenType,
		Scopes:       apiToken.Scopes,
		CreationTime: apiToken.CreationTime,
	})
}

func invalidateAPITokensCreatedByOperatorIDAndOperationID(operatorID int, operatorUsername string, operationID int) error {
	var err error
	if operationID > 0 {
		_, err = database.DB.Exec(`UPDATE apitokens
			SET active=false, deleted=true
			FROM operator bot_operator
			WHERE apitokens.created_by=$1
			  AND apitokens.operator_id = bot_operator.id
			  AND apitokens.operator_id != apitokens.created_by
			  AND bot_operator.account_type='bot'
			  AND bot_operator.current_operation_id=$2
			RETURNING apitokens.id
			`,
			operatorID, operationID)
		go rabbitmq.SendAllOperationsMessage(fmt.Sprintf("Invalidating APITokens created by %s for bot accounts", operatorUsername),
			operationID, "", database.MESSAGE_LEVEL_INFO, false)
	} else {
		_, err = database.DB.Exec(`UPDATE apitokens
			SET active=false, deleted=true
			FROM operator bot_operator
			WHERE apitokens.created_by=$1
			  AND apitokens.operator_id = bot_operator.id
			  AND apitokens.operator_id != apitokens.created_by
			  AND bot_operator.account_type='bot'
			RETURNING apitokens.id`,
			operatorID)
	}

	return err
}
