import React from 'react';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import { PayloadsTableRow } from './PayloadsTableRow';
import {ImportPayloadConfigDialog} from './ImportPayloadConfigDialog';
import { MythicDialog } from '../../MythicComponents/MythicDialog';
import {useNavigate} from 'react-router-dom';
import { Backdrop } from '@mui/material';
import {MythicPageHeader, MythicPageHeaderChip} from "../../MythicComponents/MythicPageHeader";
import {MythicTablePagination} from "../../MythicComponents/MythicTablePagination";
import {MythicToolbarButton, MythicToolbarToggle} from "../../MythicComponents/MythicTableToolbar";
import {MythicLoadingState, MythicTableEmptyState} from "../../MythicComponents/MythicStateDisplay";
import AddCircleIcon from '@mui/icons-material/AddCircle';
import FileUploadIcon from '@mui/icons-material/FileUpload';
import Inventory2Icon from '@mui/icons-material/Inventory2';
import VisibilityOffIcon from '@mui/icons-material/VisibilityOff';
import VisibilityIcon from '@mui/icons-material/Visibility';


export function PayloadsTable({payload, onDeletePayload, onUpdateCallbackAlert, onRestorePayload, me,
                                  pageData, onChangePage, onChangeShowDeleted, onChangeShowAutogenerated,
                                  onCallbacksAllowedChanged, openBackdrop}){
    const [showDeleted, setShowDeleted] = React.useState(false);
    const [showAutogenerated, setShowAutogenerated] = React.useState(false);
    const [openPayloadImport, setOpenPayloadImport] = React.useState(false);
    const navigate = useNavigate();
    const toggleShowDeleted = () => {
        setShowDeleted(!showDeleted);
        onChangeShowDeleted(!showDeleted);
    }
    const toggleShowAutogenerated = () => {
        setShowAutogenerated(!showAutogenerated);
        onChangeShowAutogenerated(!showAutogenerated);
    }
    const payloadCountLabel = payload.length === 1 ? "1 shown" : `${payload.length} shown`;
    const totalCountLabel = pageData.totalCount === 1 ? "1 total" : `${pageData.totalCount} total`;
    return (
        <>
            <MythicPageHeader
                title={"Payloads"}
                subtitle={"Build, import, and manage payload artifacts for the current operation."}
                meta={
                    <>
                        <MythicPageHeaderChip label={payloadCountLabel} />
                        <MythicPageHeaderChip label={totalCountLabel} />
                        {showDeleted && <MythicPageHeaderChip label="Deleted visible" />}
                        {showAutogenerated && <MythicPageHeaderChip label="Autogenerated" />}
                    </>
                }
                actions={
                    <>
                        <MythicToolbarButton variant="contained" color="primary" startIcon={<AddCircleIcon />} onClick={() => navigate("/new/createpayload")}>
                            Payload
                        </MythicToolbarButton>
                        <MythicToolbarButton variant="outlined" color="primary" startIcon={<Inventory2Icon />} onClick={() => navigate("/new/createwrapper")}>
                            Wrapper
                        </MythicToolbarButton>
                        <MythicToolbarButton variant="outlined" color="primary" startIcon={<FileUploadIcon />} onClick={() => setOpenPayloadImport(true)}>
                            Import Config
                        </MythicToolbarButton>
                        <MythicToolbarToggle
                            checked={showDeleted}
                            onClick={toggleShowDeleted}
                            label="Deleted"
                            activeIcon={<VisibilityIcon fontSize="small" />}
                            inactiveIcon={<VisibilityOffIcon fontSize="small" />}
                        />
                        <MythicToolbarToggle
                            checked={showAutogenerated}
                            onClick={toggleShowAutogenerated}
                            label="Autogenerated"
                            activeIcon={<VisibilityIcon fontSize="small" />}
                            inactiveIcon={<VisibilityOffIcon fontSize="small" />}
                        />
                    </>
                }
            />
            {openPayloadImport &&
                <MythicDialog fullWidth={true} maxWidth="sm" open={openPayloadImport}
                              onClose={()=>{setOpenPayloadImport(false);}}
                              innerDialog={<ImportPayloadConfigDialog onClose={()=>{setOpenPayloadImport(false);}} />}
                />
            }
            <div style={{display: "flex", flexDirection: "column", flexGrow: 1, minHeight: 0, position: "relative"}}>
                {openBackdrop &&
                    <Backdrop open={openBackdrop} style={{zIndex: 2000, position: "absolute"}}>
                        <MythicLoadingState compact title="Loading payloads" description="Fetching payload records for this page." sx={{color: "inherit"}} />
                    </Backdrop>
                }
            <TableContainer className="mythicElement" style={{flexGrow: 1, overflowY: "auto", height: "100%"}}>
                <Table stickyHeader size="small" style={{maxWidth: "100%", tableLayout: "fixed"}}>
                    <TableHead >
                        <TableRow>
                        <TableCell style={{width: "6rem"}}></TableCell>
                        <TableCell style={{width: "3rem"}}></TableCell>
                        <TableCell>File</TableCell>
                        <TableCell style={{width: "18rem"}}>Progress</TableCell>
                        <TableCell>Description</TableCell>
                            <TableCell >C2 Status</TableCell>
                            <TableCell>Tags</TableCell>
                        </TableRow>
                    </TableHead>
                    <TableBody>
                        {payload.length === 0 && !openBackdrop &&
                            <MythicTableEmptyState
                                colSpan={7}
                                compact
                                title={showDeleted || showAutogenerated ? "No payloads match this view" : "No payloads yet"}
                                description={showDeleted || showAutogenerated ? "Try changing the deleted or autogenerated filters." : "Created payloads and imported configs will appear here."}
                            />
                        }
                        {payload.map( (op) => (
                            <PayloadsTableRow
                                me={me}
                                onDeletePayload={onDeletePayload}
                                onAlertChanged={onUpdateCallbackAlert}
                                showDeleted={showDeleted}
                                onRestorePayload={onRestorePayload}
                                onCallbacksAllowedChanged={onCallbacksAllowedChanged}
                                key={"payload" + op.id}
                                {...op}
                            />
                        ))}
                    </TableBody>
                </Table>
            </TableContainer>
            </div>
            <MythicTablePagination totalCount={pageData.totalCount} fetchLimit={pageData.fetchLimit} onChange={onChangePage} />
        </>

    )
}
