-- +migrate Up
-- SQL in section 'Up' is executed when this migration is applied

create table if not exists "public"."operator_alias" (
    id integer generated by default as identity primary key,
    operator_id integer not null references "public"."operator"(id) on update restrict on delete cascade,
    name text not null,
    alias text not null,
    alias_type text not null default 'command',
    payloadtype_id integer references "public"."payloadtype"(id) on update restrict on delete cascade,
    consuming_container_id integer references "public"."consuming_container"(id) on update restrict on delete cascade,
    active boolean not null default true,
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone not null default now(),
    constraint operator_alias_scope_check check (payloadtype_id is null or consuming_container_id is null),
    constraint operator_alias_type_check check (alias_type in ('command', 'generic')),
    constraint operator_alias_name_check check (name ~ '^[a-z][a-z0-9_-]*$'),
    constraint operator_alias_alias_check check (length(trim(alias)) > 0)
);

create unique index if not exists operator_alias_operator_container_alias_unique
on "public"."operator_alias" using btree (operator_id, consuming_container_id, alias_type, name)
where consuming_container_id is not null and active=true;

create unique index if not exists operator_alias_operator_payloadtype_alias_unique
on "public"."operator_alias" using btree (operator_id, payloadtype_id, alias_type, name)
where payloadtype_id is not null and active=true;

create unique index if not exists operator_alias_operator_global_alias_unique
on "public"."operator_alias" using btree (operator_id, alias_type, name)
where payloadtype_id is null and consuming_container_id is null and active=true;

create index if not exists operator_alias_operator_container_alias_idx
on "public"."operator_alias" using btree (operator_id, consuming_container_id, alias_type, name)
where consuming_container_id is not null;

create index if not exists operator_alias_operator_payloadtype_alias_idx
on "public"."operator_alias" using btree (operator_id, payloadtype_id, alias_type, name)
where payloadtype_id is not null;

create index if not exists operator_alias_operator_global_alias_idx
on "public"."operator_alias" using btree (operator_id, alias_type, name)
where payloadtype_id is null and consuming_container_id is null;

create index if not exists operator_alias_operator_id_idx
on "public"."operator_alias" using btree (operator_id);

create index if not exists operator_alias_consuming_container_id_idx
on "public"."operator_alias" using btree (consuming_container_id);

create index if not exists operator_alias_payloadtype_id_idx
on "public"."operator_alias" using btree (payloadtype_id);

create or replace trigger set_public_operator_alias_updated_at
before update on "public"."operator_alias"
for each row execute function public.set_current_timestamp_updated_at();

alter table "public"."task" add column if not exists "alias_resolution" text not null default ''::text;
alter table "public"."task" add column if not exists "keyword_resolution" jsonb not null default '[]'::jsonb;
alter table "public"."custombrowser" add column if not exists "display_name" text not null default ''::text;
alter table "public"."eventstep" add column if not exists "deleted" boolean not null default false;

-- +migrate StatementBegin
do $$
begin
    if exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'credential'
          and column_name = 'metadata'
          and data_type <> 'jsonb'
    ) then
        alter table "public"."credential" alter column "metadata" drop default;
        alter table "public"."credential" alter column "metadata" type jsonb
            using (
                case
                    when "metadata" is null or btrim("metadata"::text) = '' then jsonb_build_object()
                    else "metadata"::jsonb
                end
            );
    end if;

    update "public"."credential"
    set "metadata" = jsonb_build_object()
    where "metadata" is null;

    alter table "public"."credential" alter column "metadata" set default jsonb_build_object();
    alter table "public"."credential" alter column "metadata" set not null;
end $$;
-- +migrate StatementEnd

create index if not exists credential_metadata_gin on "public"."credential" using gin ("metadata");

alter table "public"."credential" add column if not exists "subtype" text not null default ''::text;

alter table "public"."credential" add column if not exists "credential_identity" jsonb not null default jsonb_build_object();

alter table "public"."credential" add column if not exists "custom_display" text not null default ''::text;

create index if not exists credential_identity_gin on "public"."credential" using gin ("credential_identity");

create index if not exists credential_identity_lookup_idx
on "public"."credential" using btree (operation_id, "type", subtype, account, realm, deleted);

alter table "public"."chat_read_state"
    add column if not exists "muted" boolean not null default false;

-- +migrate StatementBegin
create or replace function public.advance_muted_chat_read_state() returns trigger
    language plpgsql
as $$
begin
    if new.author_type = 'system' then
        return new;
    end if;

    update "public"."chat_read_state" read_state
    set last_read_message_id = new.id,
        updated_at = now()
    where read_state.operation_id = new.operation_id
      and read_state.channel_id = new.channel_id
      and read_state.muted = true
      and (
        read_state.last_read_message_id is null
            or read_state.last_read_message_id < new.id
        )
      and not exists (
        select 1
        from "public"."chat_message" system_message
        where system_message.operation_id = new.operation_id
          and system_message.channel_id = new.channel_id
          and system_message.author_type = 'system'
          and (
            read_state.last_read_message_id is null
                or system_message.id > read_state.last_read_message_id
            )
          and system_message.id <= new.id
    );

    return new;
end;
$$;
-- +migrate StatementEnd

drop trigger if exists advance_muted_chat_read_state_trigger on "public"."chat_message";
create trigger advance_muted_chat_read_state_trigger
    after insert on "public"."chat_message"
    for each row execute function public.advance_muted_chat_read_state();

-- +migrate Down
-- SQL section 'Down' is executed when this migration is rolled back

drop index if exists "public"."credential_identity_lookup_idx";
drop index if exists "public"."credential_identity_gin";
alter table "public"."credential" drop column if exists "custom_display";
alter table "public"."credential" drop column if exists "credential_identity";
alter table "public"."credential" drop column if exists "subtype";
alter table "public"."eventstep" drop column if exists "deleted";
drop trigger if exists set_public_operator_alias_updated_at on "public"."operator_alias";
drop index if exists "public"."operator_alias_payloadtype_id_idx";
drop index if exists "public"."operator_alias_consuming_container_id_idx";
drop index if exists "public"."operator_alias_operator_id_idx";
drop index if exists "public"."operator_alias_operator_global_alias_idx";
drop index if exists "public"."operator_alias_operator_payloadtype_alias_idx";
drop index if exists "public"."operator_alias_operator_container_alias_idx";
drop index if exists "public"."operator_alias_operator_global_alias_unique";
drop index if exists "public"."operator_alias_operator_payloadtype_alias_unique";
drop index if exists "public"."operator_alias_operator_container_alias_unique";
drop table if exists "public"."operator_alias";
alter table "public"."task" drop column if exists "keyword_resolution";
drop trigger if exists advance_muted_chat_read_state_trigger on "public"."chat_message";
drop function if exists public.advance_muted_chat_read_state();
alter table "public"."chat_read_state" drop column if exists "muted";
