-- +migrate Up
-- SQL in section 'Up' is executed when this migration is applied

create table if not exists "public"."operator_alias" (
    id integer generated by default as identity primary key,
    operator_id integer not null references "public"."operator"(id) on update restrict on delete cascade,
    slash_command text not null,
    actual_command text not null,
    payloadtype_id integer references "public"."payloadtype"(id) on update restrict on delete cascade,
    consuming_container_id integer references "public"."consuming_container"(id) on update restrict on delete cascade,
    active boolean not null default true,
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone not null default now(),
    constraint operator_alias_scope_check check ((payloadtype_id is null) <> (consuming_container_id is null)),
    constraint operator_alias_slash_command_check check (slash_command ~ '^[a-z][a-z0-9_-]*$'),
    constraint operator_alias_actual_command_check check (length(trim(actual_command)) > 0)
);

create unique index if not exists operator_alias_operator_container_command_unique
on "public"."operator_alias" using btree (operator_id, consuming_container_id, slash_command)
where consuming_container_id is not null and active=true;

create unique index if not exists operator_alias_operator_payloadtype_command_unique
on "public"."operator_alias" using btree (operator_id, payloadtype_id, slash_command)
where payloadtype_id is not null and active=true;

create index if not exists operator_alias_operator_container_command_idx
on "public"."operator_alias" using btree (operator_id, consuming_container_id, slash_command)
where consuming_container_id is not null;

create index if not exists operator_alias_operator_payloadtype_command_idx
on "public"."operator_alias" using btree (operator_id, payloadtype_id, slash_command)
where payloadtype_id is not null;

create index if not exists operator_alias_operator_id_idx
on "public"."operator_alias" using btree (operator_id);

create index if not exists operator_alias_consuming_container_id_idx
on "public"."operator_alias" using btree (consuming_container_id);

create index if not exists operator_alias_payloadtype_id_idx
on "public"."operator_alias" using btree (payloadtype_id);

create or replace trigger set_public_operator_alias_updated_at
before update on "public"."operator_alias"
for each row execute function public.set_current_timestamp_updated_at();

alter table "public"."task" add column if not exists "alias_resolution" text not null default ''::text;
alter table "public"."custombrowser" add column if not exists "display_name" text not null default ''::text;

-- +migrate Down
-- SQL section 'Down' is executed when this migration is rolled back

drop trigger if exists set_public_operator_alias_updated_at on "public"."operator_alias";
drop index if exists "public"."operator_alias_payloadtype_id_idx";
drop index if exists "public"."operator_alias_consuming_container_id_idx";
drop index if exists "public"."operator_alias_operator_id_idx";
drop index if exists "public"."operator_alias_operator_payloadtype_command_idx";
drop index if exists "public"."operator_alias_operator_container_command_idx";
drop index if exists "public"."operator_alias_operator_payloadtype_command_unique";
drop index if exists "public"."operator_alias_operator_container_command_unique";
drop table if exists "public"."operator_alias";
