-- +migrate Up
-- SQL in section 'Up' is executed when this migration is applied

create table if not exists "public"."operation_display_counters" (
    operation_id integer primary key references "public"."operation"(id) on delete cascade,
    last_task_display_id integer not null default 0,
    last_callback_display_id integer not null default 0
);

insert into "public"."operation_display_counters" (
    operation_id,
    last_task_display_id,
    last_callback_display_id
)
select
    op.id,
    coalesce((select max(display_id) from "public"."task" where operation_id = op.id), 0),
    coalesce((select max(display_id) from "public"."callback" where operation_id = op.id), 0)
from "public"."operation" op
on conflict (operation_id) do update
set
    last_task_display_id = greatest(
        "public"."operation_display_counters".last_task_display_id,
        excluded.last_task_display_id
    ),
    last_callback_display_id = greatest(
        "public"."operation_display_counters".last_callback_display_id,
        excluded.last_callback_display_id
    );

-- +migrate StatementBegin
do $$
begin
    if exists (
        select 1
        from "public"."task"
        group by operation_id, display_id
        having count(*) > 1
    ) then
        raise exception 'Cannot add task(operation_id, display_id) uniqueness because duplicate task display IDs already exist';
    end if;

    if exists (
        select 1
        from "public"."callback"
        group by operation_id, display_id
        having count(*) > 1
    ) then
        raise exception 'Cannot add callback(operation_id, display_id) uniqueness because duplicate callback display IDs already exist';
    end if;
end $$;
-- +migrate StatementEnd

create unique index if not exists task_operation_display_id_unique
on "public"."task" using btree (operation_id, display_id);

create unique index if not exists callback_operation_display_id_unique
on "public"."callback" using btree (operation_id, display_id);

-- +migrate StatementBegin
do $$
begin
    if exists (
        select 1
        from "public"."response"
        where sequence_number is not null
        group by task_id, sequence_number
        having count(*) > 1
    ) then
        raise exception 'Cannot add response(task_id, sequence_number) uniqueness because duplicate response sequence numbers already exist';
    end if;
end $$;
-- +migrate StatementEnd

create unique index if not exists response_task_sequence_number_unique
on "public"."response" using btree (task_id, sequence_number)
where sequence_number is not null;

create index if not exists mythictree_operation_tree_host_parent_callback_idx
on "public"."mythictree" using btree (operation_id, tree_type, host, parent_path, callback_id);

create index if not exists mythictree_operation_tree_host_full_callback_idx
on "public"."mythictree" using btree (operation_id, tree_type, host, full_path, callback_id);

create index if not exists mythictree_operation_tree_timestamp_idx
on "public"."mythictree" using btree (operation_id, tree_type, "timestamp");

create index if not exists mythictree_tree_deleted_timestamp_idx
on "public"."mythictree" using btree (tree_type, deleted, "timestamp");

create index if not exists operationeventlog_unresolved_warning_source_operation_level_idx
on "public"."operationeventlog" using btree (source, operation_id, "level")
where warning=true and resolved=false and deleted=false;

create table if not exists "public"."chat_channel" (
    id integer generated by default as identity primary key,
    operation_id integer not null references "public"."operation"(id) on delete cascade,
    name text not null,
    slug text not null,
    description text not null default '',
    channel_type text not null default 'standard',
    created_by integer not null references "public"."operator"(id) on delete restrict,
    archived boolean not null default false,
    archived_by integer references "public"."operator"(id) on delete set null,
    archived_at timestamp without time zone,
    locked boolean not null default false,
    locked_by integer references "public"."operator"(id) on delete set null,
    locked_at timestamp without time zone,
    chat_container_id integer references "public"."consuming_container"(id) on delete set null,
    chat_model text not null default '',
    ai_metadata jsonb not null default jsonb_build_object(),
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone not null default now(),
    constraint chat_channel_type_check check (channel_type in ('standard', 'ai')),
    constraint chat_channel_ai_container_check check (channel_type <> 'ai' or chat_container_id is not null)
);

create unique index if not exists chat_channel_operation_slug_unique
on "public"."chat_channel" using btree (operation_id, lower(slug));

create index if not exists chat_channel_operation_type_archived_idx
on "public"."chat_channel" using btree (operation_id, channel_type, archived, name);

create or replace trigger set_public_chat_channel_updated_at
before update on "public"."chat_channel"
for each row execute function public.set_current_timestamp_updated_at();

create table if not exists "public"."chat_message" (
    id integer generated by default as identity primary key,
    operation_id integer not null references "public"."operation"(id) on delete cascade,
    channel_id integer not null references "public"."chat_channel"(id) on delete cascade,
    operator_id integer references "public"."operator"(id) on delete set null,
    apitokens_id integer references "public"."apitokens"(id) on delete set null,
    author_type text not null default 'operator',
    chat_container_id integer references "public"."consuming_container"(id) on delete set null,
    sender_display_name text not null default '',
    message text not null default '',
    deleted boolean not null default false,
    search_vector tsvector generated always as (
        to_tsvector('simple', case when deleted then '' else coalesce(message, '') end)
    ) stored,
    edited boolean not null default false,
    edited_at timestamp without time zone,
    deleted_by integer references "public"."operator"(id) on delete set null,
    deleted_at timestamp without time zone,
    status text not null default 'complete',
    metadata jsonb not null default jsonb_build_object(),
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone not null default now(),
    constraint chat_message_author_type_check check (author_type in ('operator', 'ai', 'system')),
    constraint chat_message_status_check check (status in ('pending', 'streaming', 'complete', 'error', 'cancelled'))
);

create index if not exists chat_message_operation_channel_id_idx
on "public"."chat_message" using btree (operation_id, channel_id, id desc);

create index if not exists chat_message_operation_updated_idx
on "public"."chat_message" using btree (operation_id, updated_at desc);

create index if not exists chat_message_operator_idx
on "public"."chat_message" using btree (operator_id);

create index if not exists chat_message_search_vector_idx
on "public"."chat_message" using gin (search_vector);

create or replace trigger set_public_chat_message_updated_at
before update on "public"."chat_message"
for each row execute function public.set_current_timestamp_updated_at();

alter table "public"."chat_channel"
    add column if not exists last_message_id integer;

update "public"."chat_channel" channel
set last_message_id = latest.id
from (
    select distinct on (channel_id)
        channel_id,
        id
    from "public"."chat_message"
    order by channel_id, id desc
) latest
where channel.id = latest.channel_id
and channel.last_message_id is distinct from latest.id;

create index if not exists chat_channel_operation_unread_idx
on "public"."chat_channel" using btree (operation_id, archived, last_message_id);

-- +migrate StatementBegin
create or replace function public.update_chat_channel_last_message_id() returns trigger
    language plpgsql
    as $$
begin
    update "public"."chat_channel"
    set last_message_id = new.id,
        updated_at = now()
    where id = new.channel_id
    and (last_message_id is null or last_message_id < new.id);

    return new;
end;
$$;
-- +migrate StatementEnd

create or replace trigger update_chat_channel_last_message_id_trigger
after insert on "public"."chat_message"
for each row execute function public.update_chat_channel_last_message_id();

create table if not exists "public"."chat_request" (
    id integer generated by default as identity primary key,
    operation_id integer not null references "public"."operation"(id) on delete cascade,
    channel_id integer not null references "public"."chat_channel"(id) on delete cascade,
    request_message_id integer not null references "public"."chat_message"(id) on delete cascade,
    response_message_id integer not null references "public"."chat_message"(id) on delete cascade,
    chat_container_id integer not null references "public"."consuming_container"(id) on delete restrict,
    model text not null default '',
    status text not null default 'pending',
    error text not null default '',
    context_snapshot jsonb not null default jsonb_build_object(),
    retry_of_id integer references "public"."chat_request"(id) on delete set null,
    created_by integer not null references "public"."operator"(id) on delete restrict,
    created_at timestamp without time zone not null default now(),
    updated_at timestamp without time zone not null default now(),
    completed_at timestamp without time zone,
    cancelled_at timestamp without time zone,
    constraint chat_request_status_check check (status in ('pending', 'streaming', 'complete', 'error', 'cancelled'))
);

create index if not exists chat_request_operation_channel_idx
on "public"."chat_request" using btree (operation_id, channel_id, id desc);

create index if not exists chat_request_response_message_id_idx
on "public"."chat_request" using btree (response_message_id);

create or replace trigger set_public_chat_request_updated_at
before update on "public"."chat_request"
for each row execute function public.set_current_timestamp_updated_at();

create table if not exists "public"."chat_read_state" (
    operation_id integer not null references "public"."operation"(id) on delete cascade,
    channel_id integer not null references "public"."chat_channel"(id) on delete cascade,
    operator_id integer not null references "public"."operator"(id) on delete cascade,
    last_read_message_id integer references "public"."chat_message"(id) on delete set null,
    updated_at timestamp without time zone not null default now(),
    primary key (operator_id, channel_id)
);

create index if not exists chat_read_state_operation_operator_idx
on "public"."chat_read_state" using btree (operation_id, operator_id);

create or replace trigger set_public_chat_read_state_updated_at
before update on "public"."chat_read_state"
for each row execute function public.set_current_timestamp_updated_at();

-- +migrate StatementBegin
create or replace function public.create_default_chat_channel_for_operation() returns trigger
    language plpgsql
    as $$
begin
    insert into "public"."chat_channel" (
        operation_id,
        name,
        slug,
        description,
        channel_type,
        created_by
    )
    values (
        new.id,
        'general',
        'general',
        'Default operation chat channel',
        'standard',
        new.admin_id
    )
    on conflict do nothing;

    return new;
end;
$$;
-- +migrate StatementEnd

create or replace trigger create_default_chat_channel_for_operation_trigger
after insert on "public"."operation"
for each row execute function public.create_default_chat_channel_for_operation();

insert into "public"."chat_channel" (
    operation_id,
    name,
    slug,
    description,
    channel_type,
    created_by
)
select
    operation.id,
    'general',
    'general',
    'Default operation chat channel',
    'standard',
    operation.admin_id
from "public"."operation"
on conflict do nothing;

update "public"."chat_channel"
set
    name = 'general',
    archived = false,
    archived_by = null,
    archived_at = null
where channel_type = 'standard'
    and lower(slug) = 'general'
    and (name <> 'general' or archived = true or archived_by is not null or archived_at is not null);

alter table "public"."task"
    add column if not exists subtask_callback_function_started boolean not null default false,
    add column if not exists group_callback_function_started boolean not null default false,
    add column if not exists completed_callback_function_started boolean not null default false;

-- +migrate StatementBegin
create or replace function public.new_task_display_id() returns trigger
    language plpgsql
    as $$
begin
    insert into "public"."operation_display_counters" (operation_id)
    values (new.operation_id)
    on conflict (operation_id) do nothing;

    update "public"."operation_display_counters"
    set last_task_display_id = last_task_display_id + 1
    where operation_id = new.operation_id
    returning last_task_display_id into new.display_id;

    return new;
end;
$$;
-- +migrate StatementEnd

-- +migrate StatementBegin
create or replace function public.new_callback_display_id() returns trigger
    language plpgsql
    as $$
begin
    insert into "public"."operation_display_counters" (operation_id)
    values (new.operation_id)
    on conflict (operation_id) do nothing;

    update "public"."operation_display_counters"
    set last_callback_display_id = last_callback_display_id + 1
    where operation_id = new.operation_id
    returning last_callback_display_id into new.display_id;

    return new;
end;
$$;
-- +migrate StatementEnd

update "public"."task"
set response_count = response_counts.total
from (
    select
        task.id,
        count(response.id)::integer as total
    from "public"."task"
    left join "public"."response" on response.task_id = task.id
    group by task.id
) response_counts
where task.id = response_counts.id
and task.response_count is distinct from response_counts.total;

-- +migrate StatementBegin
create or replace function public.update_task_response_count() returns trigger
    language plpgsql
    as $$
begin
    update "public"."task"
    set response_count = response_count + 1
    where id = new.task_id;

    return new;
end;
$$;
-- +migrate StatementEnd

-- +migrate Down
-- SQL in section 'Down' is executed when this migration is rolled back

-- +migrate StatementBegin
create or replace function public.update_task_response_count() returns trigger
    language plpgsql
    as $$
declare
   current_max integer;
begin
    select count(*)
    into current_max
    from response
    where task_id = new.task_id;

    update task set response_count = current_max where id = new.task_id;
    return new;
end;
$$;
-- +migrate StatementEnd

-- +migrate StatementBegin
create or replace function public.new_callback_display_id() returns trigger
    language plpgsql
    as $$
declare
   current_max integer;
begin
    select greatest(0, max(display_id))
    into current_max
    from callback
    where operation_id = new.operation_id;

    new.display_id := current_max + 1;
    return new;
end;
$$;
-- +migrate StatementEnd

-- +migrate StatementBegin
create or replace function public.new_task_display_id() returns trigger
    language plpgsql
    as $$
declare
   current_max integer;
begin
    select greatest(0, max(display_id))
    into current_max
    from task
    where operation_id = new.operation_id;

    new.display_id := current_max + 1;
    return new;
end;
$$;
-- +migrate StatementEnd

drop index if exists "public"."callback_operation_display_id_unique";
drop index if exists "public"."task_operation_display_id_unique";
drop index if exists "public"."response_task_sequence_number_unique";
drop index if exists "public"."mythictree_tree_deleted_timestamp_idx";
drop index if exists "public"."mythictree_operation_tree_timestamp_idx";
drop index if exists "public"."mythictree_operation_tree_host_full_callback_idx";
drop index if exists "public"."mythictree_operation_tree_host_parent_callback_idx";
drop index if exists "public"."operationeventlog_unresolved_warning_source_operation_level_idx";
drop index if exists "public"."chat_channel_operation_unread_idx";
drop trigger if exists update_chat_channel_last_message_id_trigger on "public"."chat_message";
drop function if exists public.update_chat_channel_last_message_id();
drop trigger if exists create_default_chat_channel_for_operation_trigger on "public"."operation";
drop function if exists public.create_default_chat_channel_for_operation();
drop table if exists "public"."chat_read_state";
drop table if exists "public"."chat_request";
drop table if exists "public"."chat_message";
drop table if exists "public"."chat_channel";
alter table "public"."task"
    drop column if exists completed_callback_function_started,
    drop column if exists group_callback_function_started,
    drop column if exists subtask_callback_function_started;
drop table if exists "public"."operation_display_counters";
