-- +migrate Up
-- SQL in section 'Up' is executed when this migration is applied

alter table "public"."eventstep"
    add column if not exists "user_interaction" jsonb not null default jsonb_build_object();

alter table "public"."eventstepinstance"
    add column if not exists "user_interaction" jsonb not null default jsonb_build_object(),
    add column if not exists "user_interaction_response" jsonb not null default jsonb_build_object(),
    add column if not exists "user_interaction_resolved_by" integer,
    add column if not exists "user_interaction_resolved_at" timestamp without time zone;

alter table "public"."eventstepinstance" drop constraint if exists "eventstepinstance_user_interaction_resolved_by_fkey";
alter table "public"."eventstepinstance" add constraint "eventstepinstance_user_interaction_resolved_by_fkey"
    foreign key ("user_interaction_resolved_by") references "public"."operator"("id") on update restrict on delete restrict not valid;
alter table "public"."eventstepinstance" validate constraint "eventstepinstance_user_interaction_resolved_by_fkey";

alter table "public"."chat_channel"
    add column if not exists "apitokens_id" integer;

alter table "public"."chat_channel" drop constraint if exists "chat_channel_apitokens_id_fkey";
alter table "public"."chat_channel" add constraint "chat_channel_apitokens_id_fkey"
    foreign key ("apitokens_id") references "public"."apitokens"("id") on update restrict on delete restrict not valid;
alter table "public"."chat_channel" validate constraint "chat_channel_apitokens_id_fkey";

alter table "public"."chat_channel" drop constraint if exists "chat_channel_ai_apitoken_check";
alter table "public"."chat_channel" add constraint "chat_channel_ai_apitoken_check"
    check (channel_type <> 'ai' or apitokens_id is not null) not valid;

create index if not exists chat_channel_apitokens_id_idx
on "public"."chat_channel" using btree (apitokens_id);

alter table "public"."apitokens"
    add column if not exists "chat_channel_id" integer;

alter table "public"."apitokens" drop constraint if exists "apitokens_chat_channel_id_fkey";
alter table "public"."apitokens" add constraint "apitokens_chat_channel_id_fkey"
    foreign key ("chat_channel_id") references "public"."chat_channel"("id") on update restrict on delete restrict not valid;
alter table "public"."apitokens" validate constraint "apitokens_chat_channel_id_fkey";

create index if not exists apitokens_chat_channel_id_idx
on "public"."apitokens" using btree (chat_channel_id);

create table if not exists "public"."c2profile_file_host" (
    id integer generated by default as identity primary key,
    operation_id integer not null references "public"."operation"(id) on delete cascade,
    filemeta_id integer not null references "public"."filemeta"(id) on delete cascade,
    c2_profile_id integer not null references "public"."c2profile"(id) on delete cascade,
    host_url text not null,
    alert_on_download boolean not null default false,
    status text not null default 'active',
    error text not null default '',
    created_by integer not null references "public"."operator"(id) on delete restrict,
    apitokens_id integer references "public"."apitokens"(id) on delete set null,
    eventstepinstance_id integer references "public"."eventstepinstance"(id) on delete set null,
    updated_at timestamp without time zone not null default now(),
    constraint c2profile_file_host_status_check check (status in ('active', 'error', 'updating', 'stopped'))
);

create unique index if not exists c2profile_file_host_profile_url_unique
on "public"."c2profile_file_host" using btree (c2_profile_id, host_url);

create index if not exists c2profile_file_host_operation_status_idx
on "public"."c2profile_file_host" using btree (operation_id, status, updated_at desc);

create index if not exists c2profile_file_host_filemeta_idx
on "public"."c2profile_file_host" using btree (filemeta_id);

create index if not exists c2profile_file_host_apitokens_id_idx
on "public"."c2profile_file_host" using btree (apitokens_id);

create index if not exists c2profile_file_host_eventstepinstance_id_idx
on "public"."c2profile_file_host" using btree (eventstepinstance_id);

create or replace trigger set_public_c2profile_file_host_updated_at
before update on "public"."c2profile_file_host"
for each row execute function public.set_current_timestamp_updated_at();

insert into "public"."c2profile_file_host"
(operation_id, filemeta_id, c2_profile_id, host_url, alert_on_download, status, error, created_by, apitokens_id, eventstepinstance_id)
select distinct on (c2profile.id, hosted.value ->> 'host_url')
    filemeta.operation_id,
    filemeta.id,
    c2profile.id,
    hosted.value ->> 'host_url',
    coalesce((hosted.value ->> 'alert_on_download')::boolean, false),
    'error',
    'Migrated from FileHosted tag; waiting for automatic C2 file hosting resync',
    filemeta.operator_id,
    coalesce(tag.apitokens_id, filemeta.apitokens_id),
    coalesce(tag.eventstepinstance_id, filemeta.eventstepinstance_id)
from "public"."tag" tag
join "public"."tagtype" tagtype on tag.tagtype_id = tagtype.id
join "public"."filemeta" filemeta on tag.filemeta_id = filemeta.id
join lateral jsonb_each(
    case
        when jsonb_typeof(tag.data::jsonb) = 'object' then tag.data::jsonb
        else '{}'::jsonb
    end
) hosted(key, value) on true
join "public"."c2profile" c2profile on c2profile.name = hosted.value ->> 'c2_profile'
where tagtype.name = 'FileHosted'
  and hosted.value ->> 'host_url' is not null
  and hosted.value ->> 'host_url' <> ''
on conflict (c2_profile_id, host_url) do nothing;

-- +migrate Down
-- SQL section 'Down' is executed when this migration is rolled back

drop trigger if exists set_public_c2profile_file_host_updated_at on "public"."c2profile_file_host";
drop index if exists "public"."c2profile_file_host_eventstepinstance_id_idx";
drop index if exists "public"."c2profile_file_host_apitokens_id_idx";
drop index if exists "public"."c2profile_file_host_filemeta_idx";
drop index if exists "public"."c2profile_file_host_operation_status_idx";
drop index if exists "public"."c2profile_file_host_profile_url_unique";
drop table if exists "public"."c2profile_file_host";

drop index if exists "public"."apitokens_chat_channel_id_idx";
alter table "public"."apitokens" drop constraint if exists "apitokens_chat_channel_id_fkey";
alter table "public"."apitokens"
    drop column if exists "chat_channel_id";

drop index if exists "public"."chat_channel_apitokens_id_idx";
alter table "public"."chat_channel" drop constraint if exists "chat_channel_ai_apitoken_check";
alter table "public"."chat_channel" drop constraint if exists "chat_channel_apitokens_id_fkey";
alter table "public"."chat_channel"
    drop column if exists "apitokens_id";

alter table "public"."eventstepinstance" drop constraint if exists "eventstepinstance_user_interaction_resolved_by_fkey";

alter table "public"."eventstepinstance"
    drop column if exists "user_interaction_resolved_at",
    drop column if exists "user_interaction_resolved_by",
    drop column if exists "user_interaction_response",
    drop column if exists "user_interaction";

alter table "public"."eventstep"
    drop column if exists "user_interaction";
