From itsafeaturemythic/xgolang_payload:0.0.5

RUN go get github.com/google/shlex \
    github.com/kbinani/screenshot \
    github.com/tmc/scp \
    github.com/xorrior/keyctl \
    golang.org/x/crypto/ssh \
    golang.org/x/sync/semaphore \
    github.com/gorilla/websocket
