from payload_type_base
RUN echo "deb http://download.mono-project.com/repo/debian wheezy/snapshots/3.12.0 main" | echo /etc/apt/sources.list.d/mono-xamarin.list
RUN apt-get update
RUN apt-get install -y mono-devel
