// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: pushC2GRPC.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PushC2_StartPushC2Streaming_FullMethodName          = "/pushC2Services.PushC2/StartPushC2Streaming"
	PushC2_StartPushC2StreamingOneToMany_FullMethodName = "/pushC2Services.PushC2/StartPushC2StreamingOneToMany"
)

// PushC2Client is the client API for PushC2 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PushC2Client interface {
	// rpc function(messageFromClient) messageToClient
	StartPushC2Streaming(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PushC2MessageFromAgent, PushC2MessageFromMythic], error)
	StartPushC2StreamingOneToMany(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PushC2MessageFromAgent, PushC2MessageFromMythic], error)
}

type pushC2Client struct {
	cc grpc.ClientConnInterface
}

func NewPushC2Client(cc grpc.ClientConnInterface) PushC2Client {
	return &pushC2Client{cc}
}

func (c *pushC2Client) StartPushC2Streaming(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PushC2MessageFromAgent, PushC2MessageFromMythic], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PushC2_ServiceDesc.Streams[0], PushC2_StartPushC2Streaming_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PushC2MessageFromAgent, PushC2MessageFromMythic]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PushC2_StartPushC2StreamingClient = grpc.BidiStreamingClient[PushC2MessageFromAgent, PushC2MessageFromMythic]

func (c *pushC2Client) StartPushC2StreamingOneToMany(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[PushC2MessageFromAgent, PushC2MessageFromMythic], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PushC2_ServiceDesc.Streams[1], PushC2_StartPushC2StreamingOneToMany_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PushC2MessageFromAgent, PushC2MessageFromMythic]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PushC2_StartPushC2StreamingOneToManyClient = grpc.BidiStreamingClient[PushC2MessageFromAgent, PushC2MessageFromMythic]

// PushC2Server is the server API for PushC2 service.
// All implementations must embed UnimplementedPushC2Server
// for forward compatibility.
type PushC2Server interface {
	// rpc function(messageFromClient) messageToClient
	StartPushC2Streaming(grpc.BidiStreamingServer[PushC2MessageFromAgent, PushC2MessageFromMythic]) error
	StartPushC2StreamingOneToMany(grpc.BidiStreamingServer[PushC2MessageFromAgent, PushC2MessageFromMythic]) error
	mustEmbedUnimplementedPushC2Server()
}

// UnimplementedPushC2Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPushC2Server struct{}

func (UnimplementedPushC2Server) StartPushC2Streaming(grpc.BidiStreamingServer[PushC2MessageFromAgent, PushC2MessageFromMythic]) error {
	return status.Errorf(codes.Unimplemented, "method StartPushC2Streaming not implemented")
}
func (UnimplementedPushC2Server) StartPushC2StreamingOneToMany(grpc.BidiStreamingServer[PushC2MessageFromAgent, PushC2MessageFromMythic]) error {
	return status.Errorf(codes.Unimplemented, "method StartPushC2StreamingOneToMany not implemented")
}
func (UnimplementedPushC2Server) mustEmbedUnimplementedPushC2Server() {}
func (UnimplementedPushC2Server) testEmbeddedByValue()                {}

// UnsafePushC2Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushC2Server will
// result in compilation errors.
type UnsafePushC2Server interface {
	mustEmbedUnimplementedPushC2Server()
}

func RegisterPushC2Server(s grpc.ServiceRegistrar, srv PushC2Server) {
	// If the following call pancis, it indicates UnimplementedPushC2Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PushC2_ServiceDesc, srv)
}

func _PushC2_StartPushC2Streaming_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PushC2Server).StartPushC2Streaming(&grpc.GenericServerStream[PushC2MessageFromAgent, PushC2MessageFromMythic]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PushC2_StartPushC2StreamingServer = grpc.BidiStreamingServer[PushC2MessageFromAgent, PushC2MessageFromMythic]

func _PushC2_StartPushC2StreamingOneToMany_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PushC2Server).StartPushC2StreamingOneToMany(&grpc.GenericServerStream[PushC2MessageFromAgent, PushC2MessageFromMythic]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PushC2_StartPushC2StreamingOneToManyServer = grpc.BidiStreamingServer[PushC2MessageFromAgent, PushC2MessageFromMythic]

// PushC2_ServiceDesc is the grpc.ServiceDesc for PushC2 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PushC2_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pushC2Services.PushC2",
	HandlerType: (*PushC2Server)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartPushC2Streaming",
			Handler:       _PushC2_StartPushC2Streaming_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "StartPushC2StreamingOneToMany",
			Handler:       _PushC2_StartPushC2StreamingOneToMany_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pushC2GRPC.proto",
}
