// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: translationContainerGRPC.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TranslationContainer_TranslateFromCustomToMythicFormat_FullMethodName = "/translationContainerServices.TranslationContainer/TranslateFromCustomToMythicFormat"
	TranslationContainer_TranslateFromMythicToCustomFormat_FullMethodName = "/translationContainerServices.TranslationContainer/TranslateFromMythicToCustomFormat"
	TranslationContainer_GenerateEncryptionKeys_FullMethodName            = "/translationContainerServices.TranslationContainer/GenerateEncryptionKeys"
)

// TranslationContainerClient is the client API for TranslationContainer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TranslationContainerClient interface {
	// rpc function(messageFromClient) messageToClient
	// all of these functions start off by sending messageToClient and getting the result back
	TranslateFromCustomToMythicFormat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TrCustomMessageToMythicC2FormatMessageResponse, TrCustomMessageToMythicC2FormatMessage], error)
	TranslateFromMythicToCustomFormat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TrMythicC2ToCustomMessageFormatMessageResponse, TrMythicC2ToCustomMessageFormatMessage], error)
	GenerateEncryptionKeys(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TrGenerateEncryptionKeysMessageResponse, TrGenerateEncryptionKeysMessage], error)
}

type translationContainerClient struct {
	cc grpc.ClientConnInterface
}

func NewTranslationContainerClient(cc grpc.ClientConnInterface) TranslationContainerClient {
	return &translationContainerClient{cc}
}

func (c *translationContainerClient) TranslateFromCustomToMythicFormat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TrCustomMessageToMythicC2FormatMessageResponse, TrCustomMessageToMythicC2FormatMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TranslationContainer_ServiceDesc.Streams[0], TranslationContainer_TranslateFromCustomToMythicFormat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrCustomMessageToMythicC2FormatMessageResponse, TrCustomMessageToMythicC2FormatMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranslationContainer_TranslateFromCustomToMythicFormatClient = grpc.BidiStreamingClient[TrCustomMessageToMythicC2FormatMessageResponse, TrCustomMessageToMythicC2FormatMessage]

func (c *translationContainerClient) TranslateFromMythicToCustomFormat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TrMythicC2ToCustomMessageFormatMessageResponse, TrMythicC2ToCustomMessageFormatMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TranslationContainer_ServiceDesc.Streams[1], TranslationContainer_TranslateFromMythicToCustomFormat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrMythicC2ToCustomMessageFormatMessageResponse, TrMythicC2ToCustomMessageFormatMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranslationContainer_TranslateFromMythicToCustomFormatClient = grpc.BidiStreamingClient[TrMythicC2ToCustomMessageFormatMessageResponse, TrMythicC2ToCustomMessageFormatMessage]

func (c *translationContainerClient) GenerateEncryptionKeys(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TrGenerateEncryptionKeysMessageResponse, TrGenerateEncryptionKeysMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TranslationContainer_ServiceDesc.Streams[2], TranslationContainer_GenerateEncryptionKeys_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TrGenerateEncryptionKeysMessageResponse, TrGenerateEncryptionKeysMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranslationContainer_GenerateEncryptionKeysClient = grpc.BidiStreamingClient[TrGenerateEncryptionKeysMessageResponse, TrGenerateEncryptionKeysMessage]

// TranslationContainerServer is the server API for TranslationContainer service.
// All implementations must embed UnimplementedTranslationContainerServer
// for forward compatibility.
type TranslationContainerServer interface {
	// rpc function(messageFromClient) messageToClient
	// all of these functions start off by sending messageToClient and getting the result back
	TranslateFromCustomToMythicFormat(grpc.BidiStreamingServer[TrCustomMessageToMythicC2FormatMessageResponse, TrCustomMessageToMythicC2FormatMessage]) error
	TranslateFromMythicToCustomFormat(grpc.BidiStreamingServer[TrMythicC2ToCustomMessageFormatMessageResponse, TrMythicC2ToCustomMessageFormatMessage]) error
	GenerateEncryptionKeys(grpc.BidiStreamingServer[TrGenerateEncryptionKeysMessageResponse, TrGenerateEncryptionKeysMessage]) error
	mustEmbedUnimplementedTranslationContainerServer()
}

// UnimplementedTranslationContainerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranslationContainerServer struct{}

func (UnimplementedTranslationContainerServer) TranslateFromCustomToMythicFormat(grpc.BidiStreamingServer[TrCustomMessageToMythicC2FormatMessageResponse, TrCustomMessageToMythicC2FormatMessage]) error {
	return status.Errorf(codes.Unimplemented, "method TranslateFromCustomToMythicFormat not implemented")
}
func (UnimplementedTranslationContainerServer) TranslateFromMythicToCustomFormat(grpc.BidiStreamingServer[TrMythicC2ToCustomMessageFormatMessageResponse, TrMythicC2ToCustomMessageFormatMessage]) error {
	return status.Errorf(codes.Unimplemented, "method TranslateFromMythicToCustomFormat not implemented")
}
func (UnimplementedTranslationContainerServer) GenerateEncryptionKeys(grpc.BidiStreamingServer[TrGenerateEncryptionKeysMessageResponse, TrGenerateEncryptionKeysMessage]) error {
	return status.Errorf(codes.Unimplemented, "method GenerateEncryptionKeys not implemented")
}
func (UnimplementedTranslationContainerServer) mustEmbedUnimplementedTranslationContainerServer() {}
func (UnimplementedTranslationContainerServer) testEmbeddedByValue()                              {}

// UnsafeTranslationContainerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranslationContainerServer will
// result in compilation errors.
type UnsafeTranslationContainerServer interface {
	mustEmbedUnimplementedTranslationContainerServer()
}

func RegisterTranslationContainerServer(s grpc.ServiceRegistrar, srv TranslationContainerServer) {
	// If the following call pancis, it indicates UnimplementedTranslationContainerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TranslationContainer_ServiceDesc, srv)
}

func _TranslationContainer_TranslateFromCustomToMythicFormat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TranslationContainerServer).TranslateFromCustomToMythicFormat(&grpc.GenericServerStream[TrCustomMessageToMythicC2FormatMessageResponse, TrCustomMessageToMythicC2FormatMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranslationContainer_TranslateFromCustomToMythicFormatServer = grpc.BidiStreamingServer[TrCustomMessageToMythicC2FormatMessageResponse, TrCustomMessageToMythicC2FormatMessage]

func _TranslationContainer_TranslateFromMythicToCustomFormat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TranslationContainerServer).TranslateFromMythicToCustomFormat(&grpc.GenericServerStream[TrMythicC2ToCustomMessageFormatMessageResponse, TrMythicC2ToCustomMessageFormatMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranslationContainer_TranslateFromMythicToCustomFormatServer = grpc.BidiStreamingServer[TrMythicC2ToCustomMessageFormatMessageResponse, TrMythicC2ToCustomMessageFormatMessage]

func _TranslationContainer_GenerateEncryptionKeys_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TranslationContainerServer).GenerateEncryptionKeys(&grpc.GenericServerStream[TrGenerateEncryptionKeysMessageResponse, TrGenerateEncryptionKeysMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TranslationContainer_GenerateEncryptionKeysServer = grpc.BidiStreamingServer[TrGenerateEncryptionKeysMessageResponse, TrGenerateEncryptionKeysMessage]

// TranslationContainer_ServiceDesc is the grpc.ServiceDesc for TranslationContainer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranslationContainer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "translationContainerServices.TranslationContainer",
	HandlerType: (*TranslationContainerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TranslateFromCustomToMythicFormat",
			Handler:       _TranslationContainer_TranslateFromCustomToMythicFormat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "TranslateFromMythicToCustomFormat",
			Handler:       _TranslationContainer_TranslateFromMythicToCustomFormat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GenerateEncryptionKeys",
			Handler:       _TranslationContainer_GenerateEncryptionKeys_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "translationContainerGRPC.proto",
}
