// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: translationContainerGRPC.proto

package services

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TranslationContainerClient is the client API for TranslationContainer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TranslationContainerClient interface {
	// rpc function(messageFromClient) messageToClient
	// all of these functions start off by sending messageToClient and getting the result back
	TranslateFromCustomToMythicFormat(ctx context.Context, opts ...grpc.CallOption) (TranslationContainer_TranslateFromCustomToMythicFormatClient, error)
	TranslateFromMythicToCustomFormat(ctx context.Context, opts ...grpc.CallOption) (TranslationContainer_TranslateFromMythicToCustomFormatClient, error)
	GenerateEncryptionKeys(ctx context.Context, opts ...grpc.CallOption) (TranslationContainer_GenerateEncryptionKeysClient, error)
}

type translationContainerClient struct {
	cc grpc.ClientConnInterface
}

func NewTranslationContainerClient(cc grpc.ClientConnInterface) TranslationContainerClient {
	return &translationContainerClient{cc}
}

func (c *translationContainerClient) TranslateFromCustomToMythicFormat(ctx context.Context, opts ...grpc.CallOption) (TranslationContainer_TranslateFromCustomToMythicFormatClient, error) {
	stream, err := c.cc.NewStream(ctx, &TranslationContainer_ServiceDesc.Streams[0], "/translationContainerServices.TranslationContainer/TranslateFromCustomToMythicFormat", opts...)
	if err != nil {
		return nil, err
	}
	x := &translationContainerTranslateFromCustomToMythicFormatClient{stream}
	return x, nil
}

type TranslationContainer_TranslateFromCustomToMythicFormatClient interface {
	Send(*TrCustomMessageToMythicC2FormatMessageResponse) error
	Recv() (*TrCustomMessageToMythicC2FormatMessage, error)
	grpc.ClientStream
}

type translationContainerTranslateFromCustomToMythicFormatClient struct {
	grpc.ClientStream
}

func (x *translationContainerTranslateFromCustomToMythicFormatClient) Send(m *TrCustomMessageToMythicC2FormatMessageResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *translationContainerTranslateFromCustomToMythicFormatClient) Recv() (*TrCustomMessageToMythicC2FormatMessage, error) {
	m := new(TrCustomMessageToMythicC2FormatMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *translationContainerClient) TranslateFromMythicToCustomFormat(ctx context.Context, opts ...grpc.CallOption) (TranslationContainer_TranslateFromMythicToCustomFormatClient, error) {
	stream, err := c.cc.NewStream(ctx, &TranslationContainer_ServiceDesc.Streams[1], "/translationContainerServices.TranslationContainer/TranslateFromMythicToCustomFormat", opts...)
	if err != nil {
		return nil, err
	}
	x := &translationContainerTranslateFromMythicToCustomFormatClient{stream}
	return x, nil
}

type TranslationContainer_TranslateFromMythicToCustomFormatClient interface {
	Send(*TrMythicC2ToCustomMessageFormatMessageResponse) error
	Recv() (*TrMythicC2ToCustomMessageFormatMessage, error)
	grpc.ClientStream
}

type translationContainerTranslateFromMythicToCustomFormatClient struct {
	grpc.ClientStream
}

func (x *translationContainerTranslateFromMythicToCustomFormatClient) Send(m *TrMythicC2ToCustomMessageFormatMessageResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *translationContainerTranslateFromMythicToCustomFormatClient) Recv() (*TrMythicC2ToCustomMessageFormatMessage, error) {
	m := new(TrMythicC2ToCustomMessageFormatMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *translationContainerClient) GenerateEncryptionKeys(ctx context.Context, opts ...grpc.CallOption) (TranslationContainer_GenerateEncryptionKeysClient, error) {
	stream, err := c.cc.NewStream(ctx, &TranslationContainer_ServiceDesc.Streams[2], "/translationContainerServices.TranslationContainer/GenerateEncryptionKeys", opts...)
	if err != nil {
		return nil, err
	}
	x := &translationContainerGenerateEncryptionKeysClient{stream}
	return x, nil
}

type TranslationContainer_GenerateEncryptionKeysClient interface {
	Send(*TrGenerateEncryptionKeysMessageResponse) error
	Recv() (*TrGenerateEncryptionKeysMessage, error)
	grpc.ClientStream
}

type translationContainerGenerateEncryptionKeysClient struct {
	grpc.ClientStream
}

func (x *translationContainerGenerateEncryptionKeysClient) Send(m *TrGenerateEncryptionKeysMessageResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *translationContainerGenerateEncryptionKeysClient) Recv() (*TrGenerateEncryptionKeysMessage, error) {
	m := new(TrGenerateEncryptionKeysMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TranslationContainerServer is the server API for TranslationContainer service.
// All implementations must embed UnimplementedTranslationContainerServer
// for forward compatibility
type TranslationContainerServer interface {
	// rpc function(messageFromClient) messageToClient
	// all of these functions start off by sending messageToClient and getting the result back
	TranslateFromCustomToMythicFormat(TranslationContainer_TranslateFromCustomToMythicFormatServer) error
	TranslateFromMythicToCustomFormat(TranslationContainer_TranslateFromMythicToCustomFormatServer) error
	GenerateEncryptionKeys(TranslationContainer_GenerateEncryptionKeysServer) error
	mustEmbedUnimplementedTranslationContainerServer()
}

// UnimplementedTranslationContainerServer must be embedded to have forward compatible implementations.
type UnimplementedTranslationContainerServer struct {
}

func (UnimplementedTranslationContainerServer) TranslateFromCustomToMythicFormat(TranslationContainer_TranslateFromCustomToMythicFormatServer) error {
	return status.Errorf(codes.Unimplemented, "method TranslateFromCustomToMythicFormat not implemented")
}
func (UnimplementedTranslationContainerServer) TranslateFromMythicToCustomFormat(TranslationContainer_TranslateFromMythicToCustomFormatServer) error {
	return status.Errorf(codes.Unimplemented, "method TranslateFromMythicToCustomFormat not implemented")
}
func (UnimplementedTranslationContainerServer) GenerateEncryptionKeys(TranslationContainer_GenerateEncryptionKeysServer) error {
	return status.Errorf(codes.Unimplemented, "method GenerateEncryptionKeys not implemented")
}
func (UnimplementedTranslationContainerServer) mustEmbedUnimplementedTranslationContainerServer() {}

// UnsafeTranslationContainerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranslationContainerServer will
// result in compilation errors.
type UnsafeTranslationContainerServer interface {
	mustEmbedUnimplementedTranslationContainerServer()
}

func RegisterTranslationContainerServer(s grpc.ServiceRegistrar, srv TranslationContainerServer) {
	s.RegisterService(&TranslationContainer_ServiceDesc, srv)
}

func _TranslationContainer_TranslateFromCustomToMythicFormat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TranslationContainerServer).TranslateFromCustomToMythicFormat(&translationContainerTranslateFromCustomToMythicFormatServer{stream})
}

type TranslationContainer_TranslateFromCustomToMythicFormatServer interface {
	Send(*TrCustomMessageToMythicC2FormatMessage) error
	Recv() (*TrCustomMessageToMythicC2FormatMessageResponse, error)
	grpc.ServerStream
}

type translationContainerTranslateFromCustomToMythicFormatServer struct {
	grpc.ServerStream
}

func (x *translationContainerTranslateFromCustomToMythicFormatServer) Send(m *TrCustomMessageToMythicC2FormatMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *translationContainerTranslateFromCustomToMythicFormatServer) Recv() (*TrCustomMessageToMythicC2FormatMessageResponse, error) {
	m := new(TrCustomMessageToMythicC2FormatMessageResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TranslationContainer_TranslateFromMythicToCustomFormat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TranslationContainerServer).TranslateFromMythicToCustomFormat(&translationContainerTranslateFromMythicToCustomFormatServer{stream})
}

type TranslationContainer_TranslateFromMythicToCustomFormatServer interface {
	Send(*TrMythicC2ToCustomMessageFormatMessage) error
	Recv() (*TrMythicC2ToCustomMessageFormatMessageResponse, error)
	grpc.ServerStream
}

type translationContainerTranslateFromMythicToCustomFormatServer struct {
	grpc.ServerStream
}

func (x *translationContainerTranslateFromMythicToCustomFormatServer) Send(m *TrMythicC2ToCustomMessageFormatMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *translationContainerTranslateFromMythicToCustomFormatServer) Recv() (*TrMythicC2ToCustomMessageFormatMessageResponse, error) {
	m := new(TrMythicC2ToCustomMessageFormatMessageResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TranslationContainer_GenerateEncryptionKeys_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TranslationContainerServer).GenerateEncryptionKeys(&translationContainerGenerateEncryptionKeysServer{stream})
}

type TranslationContainer_GenerateEncryptionKeysServer interface {
	Send(*TrGenerateEncryptionKeysMessage) error
	Recv() (*TrGenerateEncryptionKeysMessageResponse, error)
	grpc.ServerStream
}

type translationContainerGenerateEncryptionKeysServer struct {
	grpc.ServerStream
}

func (x *translationContainerGenerateEncryptionKeysServer) Send(m *TrGenerateEncryptionKeysMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *translationContainerGenerateEncryptionKeysServer) Recv() (*TrGenerateEncryptionKeysMessageResponse, error) {
	m := new(TrGenerateEncryptionKeysMessageResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TranslationContainer_ServiceDesc is the grpc.ServiceDesc for TranslationContainer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TranslationContainer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "translationContainerServices.TranslationContainer",
	HandlerType: (*TranslationContainerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TranslateFromCustomToMythicFormat",
			Handler:       _TranslationContainer_TranslateFromCustomToMythicFormat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "TranslateFromMythicToCustomFormat",
			Handler:       _TranslationContainer_TranslateFromMythicToCustomFormat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GenerateEncryptionKeys",
			Handler:       _TranslationContainer_GenerateEncryptionKeys_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "translationContainerGRPC.proto",
}
