// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: translationContainerGRPC.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TrCustomMessageToMythicC2FormatMessage struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	TranslationContainerName string                 `protobuf:"bytes,1,opt,name=TranslationContainerName,proto3" json:"TranslationContainerName,omitempty"`
	C2Name                   string                 `protobuf:"bytes,2,opt,name=C2Name,proto3" json:"C2Name,omitempty"`
	Message                  []byte                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	UUID                     string                 `protobuf:"bytes,4,opt,name=UUID,proto3" json:"UUID,omitempty"`
	MythicEncrypts           bool                   `protobuf:"varint,5,opt,name=MythicEncrypts,proto3" json:"MythicEncrypts,omitempty"`
	CryptoKeys               []*CryptoKeysFormat    `protobuf:"bytes,6,rep,name=CryptoKeys,proto3" json:"CryptoKeys,omitempty"`
	AuthContext              string                 `protobuf:"bytes,7,opt,name=AuthContext,proto3" json:"AuthContext,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TrCustomMessageToMythicC2FormatMessage) Reset() {
	*x = TrCustomMessageToMythicC2FormatMessage{}
	mi := &file_translationContainerGRPC_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrCustomMessageToMythicC2FormatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrCustomMessageToMythicC2FormatMessage) ProtoMessage() {}

func (x *TrCustomMessageToMythicC2FormatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_translationContainerGRPC_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrCustomMessageToMythicC2FormatMessage.ProtoReflect.Descriptor instead.
func (*TrCustomMessageToMythicC2FormatMessage) Descriptor() ([]byte, []int) {
	return file_translationContainerGRPC_proto_rawDescGZIP(), []int{0}
}

func (x *TrCustomMessageToMythicC2FormatMessage) GetTranslationContainerName() string {
	if x != nil {
		return x.TranslationContainerName
	}
	return ""
}

func (x *TrCustomMessageToMythicC2FormatMessage) GetC2Name() string {
	if x != nil {
		return x.C2Name
	}
	return ""
}

func (x *TrCustomMessageToMythicC2FormatMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *TrCustomMessageToMythicC2FormatMessage) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *TrCustomMessageToMythicC2FormatMessage) GetMythicEncrypts() bool {
	if x != nil {
		return x.MythicEncrypts
	}
	return false
}

func (x *TrCustomMessageToMythicC2FormatMessage) GetCryptoKeys() []*CryptoKeysFormat {
	if x != nil {
		return x.CryptoKeys
	}
	return nil
}

func (x *TrCustomMessageToMythicC2FormatMessage) GetAuthContext() string {
	if x != nil {
		return x.AuthContext
	}
	return ""
}

type CryptoKeysFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EncKey        []byte                 `protobuf:"bytes,1,opt,name=EncKey,proto3" json:"EncKey,omitempty"`
	DecKey        []byte                 `protobuf:"bytes,2,opt,name=DecKey,proto3" json:"DecKey,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=Location,proto3" json:"Location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CryptoKeysFormat) Reset() {
	*x = CryptoKeysFormat{}
	mi := &file_translationContainerGRPC_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoKeysFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoKeysFormat) ProtoMessage() {}

func (x *CryptoKeysFormat) ProtoReflect() protoreflect.Message {
	mi := &file_translationContainerGRPC_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoKeysFormat.ProtoReflect.Descriptor instead.
func (*CryptoKeysFormat) Descriptor() ([]byte, []int) {
	return file_translationContainerGRPC_proto_rawDescGZIP(), []int{1}
}

func (x *CryptoKeysFormat) GetEncKey() []byte {
	if x != nil {
		return x.EncKey
	}
	return nil
}

func (x *CryptoKeysFormat) GetDecKey() []byte {
	if x != nil {
		return x.DecKey
	}
	return nil
}

func (x *CryptoKeysFormat) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CryptoKeysFormat) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type TrCustomMessageToMythicC2FormatMessageResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Success                  bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Error                    string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Message                  []byte                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	TranslationContainerName string                 `protobuf:"bytes,4,opt,name=TranslationContainerName,proto3" json:"TranslationContainerName,omitempty"`
	AuthContext              string                 `protobuf:"bytes,5,opt,name=AuthContext,proto3" json:"AuthContext,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TrCustomMessageToMythicC2FormatMessageResponse) Reset() {
	*x = TrCustomMessageToMythicC2FormatMessageResponse{}
	mi := &file_translationContainerGRPC_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrCustomMessageToMythicC2FormatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrCustomMessageToMythicC2FormatMessageResponse) ProtoMessage() {}

func (x *TrCustomMessageToMythicC2FormatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translationContainerGRPC_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrCustomMessageToMythicC2FormatMessageResponse.ProtoReflect.Descriptor instead.
func (*TrCustomMessageToMythicC2FormatMessageResponse) Descriptor() ([]byte, []int) {
	return file_translationContainerGRPC_proto_rawDescGZIP(), []int{2}
}

func (x *TrCustomMessageToMythicC2FormatMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrCustomMessageToMythicC2FormatMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TrCustomMessageToMythicC2FormatMessageResponse) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *TrCustomMessageToMythicC2FormatMessageResponse) GetTranslationContainerName() string {
	if x != nil {
		return x.TranslationContainerName
	}
	return ""
}

func (x *TrCustomMessageToMythicC2FormatMessageResponse) GetAuthContext() string {
	if x != nil {
		return x.AuthContext
	}
	return ""
}

type TrMythicC2ToCustomMessageFormatMessage struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	TranslationContainerName string                 `protobuf:"bytes,1,opt,name=TranslationContainerName,proto3" json:"TranslationContainerName,omitempty"`
	C2Name                   string                 `protobuf:"bytes,2,opt,name=C2Name,proto3" json:"C2Name,omitempty"`
	Message                  []byte                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	UUID                     string                 `protobuf:"bytes,4,opt,name=UUID,proto3" json:"UUID,omitempty"`
	MythicEncrypts           bool                   `protobuf:"varint,5,opt,name=MythicEncrypts,proto3" json:"MythicEncrypts,omitempty"`
	CryptoKeys               []*CryptoKeysFormat    `protobuf:"bytes,6,rep,name=CryptoKeys,proto3" json:"CryptoKeys,omitempty"`
	AuthContext              string                 `protobuf:"bytes,7,opt,name=AuthContext,proto3" json:"AuthContext,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TrMythicC2ToCustomMessageFormatMessage) Reset() {
	*x = TrMythicC2ToCustomMessageFormatMessage{}
	mi := &file_translationContainerGRPC_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrMythicC2ToCustomMessageFormatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrMythicC2ToCustomMessageFormatMessage) ProtoMessage() {}

func (x *TrMythicC2ToCustomMessageFormatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_translationContainerGRPC_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrMythicC2ToCustomMessageFormatMessage.ProtoReflect.Descriptor instead.
func (*TrMythicC2ToCustomMessageFormatMessage) Descriptor() ([]byte, []int) {
	return file_translationContainerGRPC_proto_rawDescGZIP(), []int{3}
}

func (x *TrMythicC2ToCustomMessageFormatMessage) GetTranslationContainerName() string {
	if x != nil {
		return x.TranslationContainerName
	}
	return ""
}

func (x *TrMythicC2ToCustomMessageFormatMessage) GetC2Name() string {
	if x != nil {
		return x.C2Name
	}
	return ""
}

func (x *TrMythicC2ToCustomMessageFormatMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *TrMythicC2ToCustomMessageFormatMessage) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *TrMythicC2ToCustomMessageFormatMessage) GetMythicEncrypts() bool {
	if x != nil {
		return x.MythicEncrypts
	}
	return false
}

func (x *TrMythicC2ToCustomMessageFormatMessage) GetCryptoKeys() []*CryptoKeysFormat {
	if x != nil {
		return x.CryptoKeys
	}
	return nil
}

func (x *TrMythicC2ToCustomMessageFormatMessage) GetAuthContext() string {
	if x != nil {
		return x.AuthContext
	}
	return ""
}

type TrMythicC2ToCustomMessageFormatMessageResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Success                  bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Error                    string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Message                  []byte                 `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	TranslationContainerName string                 `protobuf:"bytes,4,opt,name=TranslationContainerName,proto3" json:"TranslationContainerName,omitempty"`
	AuthContext              string                 `protobuf:"bytes,5,opt,name=AuthContext,proto3" json:"AuthContext,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TrMythicC2ToCustomMessageFormatMessageResponse) Reset() {
	*x = TrMythicC2ToCustomMessageFormatMessageResponse{}
	mi := &file_translationContainerGRPC_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrMythicC2ToCustomMessageFormatMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrMythicC2ToCustomMessageFormatMessageResponse) ProtoMessage() {}

func (x *TrMythicC2ToCustomMessageFormatMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translationContainerGRPC_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrMythicC2ToCustomMessageFormatMessageResponse.ProtoReflect.Descriptor instead.
func (*TrMythicC2ToCustomMessageFormatMessageResponse) Descriptor() ([]byte, []int) {
	return file_translationContainerGRPC_proto_rawDescGZIP(), []int{4}
}

func (x *TrMythicC2ToCustomMessageFormatMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrMythicC2ToCustomMessageFormatMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TrMythicC2ToCustomMessageFormatMessageResponse) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *TrMythicC2ToCustomMessageFormatMessageResponse) GetTranslationContainerName() string {
	if x != nil {
		return x.TranslationContainerName
	}
	return ""
}

func (x *TrMythicC2ToCustomMessageFormatMessageResponse) GetAuthContext() string {
	if x != nil {
		return x.AuthContext
	}
	return ""
}

type TrGenerateEncryptionKeysMessage struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	TranslationContainerName string                 `protobuf:"bytes,1,opt,name=TranslationContainerName,proto3" json:"TranslationContainerName,omitempty"`
	C2Name                   string                 `protobuf:"bytes,2,opt,name=C2Name,proto3" json:"C2Name,omitempty"`
	CryptoParamValue         string                 `protobuf:"bytes,3,opt,name=CryptoParamValue,proto3" json:"CryptoParamValue,omitempty"`
	CryptoParamName          string                 `protobuf:"bytes,4,opt,name=CryptoParamName,proto3" json:"CryptoParamName,omitempty"`
	AuthContext              string                 `protobuf:"bytes,5,opt,name=AuthContext,proto3" json:"AuthContext,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TrGenerateEncryptionKeysMessage) Reset() {
	*x = TrGenerateEncryptionKeysMessage{}
	mi := &file_translationContainerGRPC_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrGenerateEncryptionKeysMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrGenerateEncryptionKeysMessage) ProtoMessage() {}

func (x *TrGenerateEncryptionKeysMessage) ProtoReflect() protoreflect.Message {
	mi := &file_translationContainerGRPC_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrGenerateEncryptionKeysMessage.ProtoReflect.Descriptor instead.
func (*TrGenerateEncryptionKeysMessage) Descriptor() ([]byte, []int) {
	return file_translationContainerGRPC_proto_rawDescGZIP(), []int{5}
}

func (x *TrGenerateEncryptionKeysMessage) GetTranslationContainerName() string {
	if x != nil {
		return x.TranslationContainerName
	}
	return ""
}

func (x *TrGenerateEncryptionKeysMessage) GetC2Name() string {
	if x != nil {
		return x.C2Name
	}
	return ""
}

func (x *TrGenerateEncryptionKeysMessage) GetCryptoParamValue() string {
	if x != nil {
		return x.CryptoParamValue
	}
	return ""
}

func (x *TrGenerateEncryptionKeysMessage) GetCryptoParamName() string {
	if x != nil {
		return x.CryptoParamName
	}
	return ""
}

func (x *TrGenerateEncryptionKeysMessage) GetAuthContext() string {
	if x != nil {
		return x.AuthContext
	}
	return ""
}

type TrGenerateEncryptionKeysMessageResponse struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Success                  bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	Error                    string                 `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	EncryptionKey            []byte                 `protobuf:"bytes,3,opt,name=EncryptionKey,proto3" json:"EncryptionKey,omitempty"`
	DecryptionKey            []byte                 `protobuf:"bytes,4,opt,name=DecryptionKey,proto3" json:"DecryptionKey,omitempty"`
	TranslationContainerName string                 `protobuf:"bytes,5,opt,name=TranslationContainerName,proto3" json:"TranslationContainerName,omitempty"`
	AuthContext              string                 `protobuf:"bytes,6,opt,name=AuthContext,proto3" json:"AuthContext,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TrGenerateEncryptionKeysMessageResponse) Reset() {
	*x = TrGenerateEncryptionKeysMessageResponse{}
	mi := &file_translationContainerGRPC_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrGenerateEncryptionKeysMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrGenerateEncryptionKeysMessageResponse) ProtoMessage() {}

func (x *TrGenerateEncryptionKeysMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_translationContainerGRPC_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrGenerateEncryptionKeysMessageResponse.ProtoReflect.Descriptor instead.
func (*TrGenerateEncryptionKeysMessageResponse) Descriptor() ([]byte, []int) {
	return file_translationContainerGRPC_proto_rawDescGZIP(), []int{6}
}

func (x *TrGenerateEncryptionKeysMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrGenerateEncryptionKeysMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TrGenerateEncryptionKeysMessageResponse) GetEncryptionKey() []byte {
	if x != nil {
		return x.EncryptionKey
	}
	return nil
}

func (x *TrGenerateEncryptionKeysMessageResponse) GetDecryptionKey() []byte {
	if x != nil {
		return x.DecryptionKey
	}
	return nil
}

func (x *TrGenerateEncryptionKeysMessageResponse) GetTranslationContainerName() string {
	if x != nil {
		return x.TranslationContainerName
	}
	return ""
}

func (x *TrGenerateEncryptionKeysMessageResponse) GetAuthContext() string {
	if x != nil {
		return x.AuthContext
	}
	return ""
}

var File_translationContainerGRPC_proto protoreflect.FileDescriptor

const file_translationContainerGRPC_proto_rawDesc = "" +
	"\n" +
	"\x1etranslationContainerGRPC.proto\x12\x1ctranslationContainerServices\"\xc4\x02\n" +
	"&TrCustomMessageToMythicC2FormatMessage\x12:\n" +
	"\x18TranslationContainerName\x18\x01 \x01(\tR\x18TranslationContainerName\x12\x16\n" +
	"\x06C2Name\x18\x02 \x01(\tR\x06C2Name\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\fR\aMessage\x12\x12\n" +
	"\x04UUID\x18\x04 \x01(\tR\x04UUID\x12&\n" +
	"\x0eMythicEncrypts\x18\x05 \x01(\bR\x0eMythicEncrypts\x12N\n" +
	"\n" +
	"CryptoKeys\x18\x06 \x03(\v2..translationContainerServices.CryptoKeysFormatR\n" +
	"CryptoKeys\x12 \n" +
	"\vAuthContext\x18\a \x01(\tR\vAuthContext\"t\n" +
	"\x10CryptoKeysFormat\x12\x16\n" +
	"\x06EncKey\x18\x01 \x01(\fR\x06EncKey\x12\x16\n" +
	"\x06DecKey\x18\x02 \x01(\fR\x06DecKey\x12\x14\n" +
	"\x05Value\x18\x03 \x01(\tR\x05Value\x12\x1a\n" +
	"\bLocation\x18\x04 \x01(\tR\bLocation\"\xd8\x01\n" +
	".TrCustomMessageToMythicC2FormatMessageResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\fR\aMessage\x12:\n" +
	"\x18TranslationContainerName\x18\x04 \x01(\tR\x18TranslationContainerName\x12 \n" +
	"\vAuthContext\x18\x05 \x01(\tR\vAuthContext\"\xc4\x02\n" +
	"&TrMythicC2ToCustomMessageFormatMessage\x12:\n" +
	"\x18TranslationContainerName\x18\x01 \x01(\tR\x18TranslationContainerName\x12\x16\n" +
	"\x06C2Name\x18\x02 \x01(\tR\x06C2Name\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\fR\aMessage\x12\x12\n" +
	"\x04UUID\x18\x04 \x01(\tR\x04UUID\x12&\n" +
	"\x0eMythicEncrypts\x18\x05 \x01(\bR\x0eMythicEncrypts\x12N\n" +
	"\n" +
	"CryptoKeys\x18\x06 \x03(\v2..translationContainerServices.CryptoKeysFormatR\n" +
	"CryptoKeys\x12 \n" +
	"\vAuthContext\x18\a \x01(\tR\vAuthContext\"\xd8\x01\n" +
	".TrMythicC2ToCustomMessageFormatMessageResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\x12\x18\n" +
	"\aMessage\x18\x03 \x01(\fR\aMessage\x12:\n" +
	"\x18TranslationContainerName\x18\x04 \x01(\tR\x18TranslationContainerName\x12 \n" +
	"\vAuthContext\x18\x05 \x01(\tR\vAuthContext\"\xed\x01\n" +
	"\x1fTrGenerateEncryptionKeysMessage\x12:\n" +
	"\x18TranslationContainerName\x18\x01 \x01(\tR\x18TranslationContainerName\x12\x16\n" +
	"\x06C2Name\x18\x02 \x01(\tR\x06C2Name\x12*\n" +
	"\x10CryptoParamValue\x18\x03 \x01(\tR\x10CryptoParamValue\x12(\n" +
	"\x0fCryptoParamName\x18\x04 \x01(\tR\x0fCryptoParamName\x12 \n" +
	"\vAuthContext\x18\x05 \x01(\tR\vAuthContext\"\x83\x02\n" +
	"'TrGenerateEncryptionKeysMessageResponse\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x14\n" +
	"\x05Error\x18\x02 \x01(\tR\x05Error\x12$\n" +
	"\rEncryptionKey\x18\x03 \x01(\fR\rEncryptionKey\x12$\n" +
	"\rDecryptionKey\x18\x04 \x01(\fR\rDecryptionKey\x12:\n" +
	"\x18TranslationContainerName\x18\x05 \x01(\tR\x18TranslationContainerName\x12 \n" +
	"\vAuthContext\x18\x06 \x01(\tR\vAuthContext2\xbd\x04\n" +
	"\x14TranslationContainer\x12\xbd\x01\n" +
	"!TranslateFromCustomToMythicFormat\x12L.translationContainerServices.TrCustomMessageToMythicC2FormatMessageResponse\x1aD.translationContainerServices.TrCustomMessageToMythicC2FormatMessage\"\x00(\x010\x01\x12\xbd\x01\n" +
	"!TranslateFromMythicToCustomFormat\x12L.translationContainerServices.TrMythicC2ToCustomMessageFormatMessageResponse\x1aD.translationContainerServices.TrMythicC2ToCustomMessageFormatMessage\"\x00(\x010\x01\x12\xa4\x01\n" +
	"\x16GenerateEncryptionKeys\x12E.translationContainerServices.TrGenerateEncryptionKeysMessageResponse\x1a=.translationContainerServices.TrGenerateEncryptionKeysMessage\"\x00(\x010\x01B/Z-github.com/its-a-feature/Mythic/grpc/servicesb\x06proto3"

var (
	file_translationContainerGRPC_proto_rawDescOnce sync.Once
	file_translationContainerGRPC_proto_rawDescData []byte
)

func file_translationContainerGRPC_proto_rawDescGZIP() []byte {
	file_translationContainerGRPC_proto_rawDescOnce.Do(func() {
		file_translationContainerGRPC_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_translationContainerGRPC_proto_rawDesc), len(file_translationContainerGRPC_proto_rawDesc)))
	})
	return file_translationContainerGRPC_proto_rawDescData
}

var file_translationContainerGRPC_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_translationContainerGRPC_proto_goTypes = []any{
	(*TrCustomMessageToMythicC2FormatMessage)(nil),         // 0: translationContainerServices.TrCustomMessageToMythicC2FormatMessage
	(*CryptoKeysFormat)(nil),                               // 1: translationContainerServices.CryptoKeysFormat
	(*TrCustomMessageToMythicC2FormatMessageResponse)(nil), // 2: translationContainerServices.TrCustomMessageToMythicC2FormatMessageResponse
	(*TrMythicC2ToCustomMessageFormatMessage)(nil),         // 3: translationContainerServices.TrMythicC2ToCustomMessageFormatMessage
	(*TrMythicC2ToCustomMessageFormatMessageResponse)(nil), // 4: translationContainerServices.TrMythicC2ToCustomMessageFormatMessageResponse
	(*TrGenerateEncryptionKeysMessage)(nil),                // 5: translationContainerServices.TrGenerateEncryptionKeysMessage
	(*TrGenerateEncryptionKeysMessageResponse)(nil),        // 6: translationContainerServices.TrGenerateEncryptionKeysMessageResponse
}
var file_translationContainerGRPC_proto_depIdxs = []int32{
	1, // 0: translationContainerServices.TrCustomMessageToMythicC2FormatMessage.CryptoKeys:type_name -> translationContainerServices.CryptoKeysFormat
	1, // 1: translationContainerServices.TrMythicC2ToCustomMessageFormatMessage.CryptoKeys:type_name -> translationContainerServices.CryptoKeysFormat
	2, // 2: translationContainerServices.TranslationContainer.TranslateFromCustomToMythicFormat:input_type -> translationContainerServices.TrCustomMessageToMythicC2FormatMessageResponse
	4, // 3: translationContainerServices.TranslationContainer.TranslateFromMythicToCustomFormat:input_type -> translationContainerServices.TrMythicC2ToCustomMessageFormatMessageResponse
	6, // 4: translationContainerServices.TranslationContainer.GenerateEncryptionKeys:input_type -> translationContainerServices.TrGenerateEncryptionKeysMessageResponse
	0, // 5: translationContainerServices.TranslationContainer.TranslateFromCustomToMythicFormat:output_type -> translationContainerServices.TrCustomMessageToMythicC2FormatMessage
	3, // 6: translationContainerServices.TranslationContainer.TranslateFromMythicToCustomFormat:output_type -> translationContainerServices.TrMythicC2ToCustomMessageFormatMessage
	5, // 7: translationContainerServices.TranslationContainer.GenerateEncryptionKeys:output_type -> translationContainerServices.TrGenerateEncryptionKeysMessage
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_translationContainerGRPC_proto_init() }
func file_translationContainerGRPC_proto_init() {
	if File_translationContainerGRPC_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_translationContainerGRPC_proto_rawDesc), len(file_translationContainerGRPC_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_translationContainerGRPC_proto_goTypes,
		DependencyIndexes: file_translationContainerGRPC_proto_depIdxs,
		MessageInfos:      file_translationContainerGRPC_proto_msgTypes,
	}.Build()
	File_translationContainerGRPC_proto = out.File
	file_translationContainerGRPC_proto_goTypes = nil
	file_translationContainerGRPC_proto_depIdxs = nil
}
